### ISSUE TITLE
Issues with hxt / serialization.

### ISSUE THREAD

**Issue by fisx** [dylex/hsaml2#2]
Hi, I am trying to get this to work on XML data generated with [xml-conduit](https://hackage.haskell.org/package/xml-conduit), and ran into two problems right at the start: both the `<?xml version="1.0"?>` instruction and namespace prefixes make `unpickleDoc` choke.  Both are certainly valid xml.  Do you have any hints what I might be doing wrong?

This is not to say "why did you pick this library and not that", but I should probably admit that I am not terribly fond of hxt.  It's huge and old and over-complicated and it uses errors, an abstraction that in my opinion buys you nothing much (an abstraction over `(->)` and `Kleisli`) for a high price (few people can read your code any more).  This is also why I'm opening this issue here (I am very interested in getting SAML-SSO to work) and not over at hxt.  Please close if you think that's obnoxious.

Thanks for this nice piece of code!

**Comment by fisx** [comment]
hm, it seems like i *am* doing something wrong, and it is indeed a problem with my using hsaml2:

```haskell
import Data.Time
import SAML2
import SAML2.XML.Canonical
import System.IO.Unsafe
import Text.XML.HXT.Arrow.Pickle.Xml.Invertible

hsamlToLT = canonicalize (CanonicalXMLExcl10 True) Nothing Nothing . pickleDoc xpickle

req = AuthnRequest
  { authnRequest = RequestAbstractType protType
  , authnRequestForceAuthn = False
  , authnRequestIsPassive = False
  , authnRequestAssertionConsumerService = AssertionConsumerServiceURL Nothing Nothing
  , authnRequestAssertionConsumingServiceIndex = Nothing
  , authnRequestProviderName = Nothing
  , authnRequestSubject = Nothing
  , authnRequestNameIDPolicy = Nothing
  , authnRequestConditions = Nothing
  , authnRequestRequestedAuthnContext = Nothing
  , authnRequestScoping = Nothing
  }

protType = ProtocolType
  { protocolID = "wef"
  , protocolVersion = SAML20
  , protocolIssueInstant = unsafePerformIO getCurrentTime
  , protocolDestination = Nothing
  , protocolConsent = Identified ConsentUnspecified
  , protocolIssuer = Nothing
  , protocolSignature = Nothing
  , protocolExtensions = []
  , relayState = Nothing
  }

main = print =<< hsamlToLT req
{-
*Main> :main
namespace error : Namespace prefix samlp on AuthnRequest is not defined
AuthnRequest ID="wef" Version="2.0" IssueInstant="2018-04-09T08:18:25.616314694"
                                                                               ^
"<samlp:AuthnRequest ID=\"wef\" IssueInstant=\"2018-04-09T08:18:25.616314694\" Version=\"2.0\"></samlp:AuthnRequest>"
-}
```

So, how do i get from `String` to `SAMLProtocol a => a` and back?

**Comment by dylex** [comment]
I should first say that while I'm happy if this is useful (and did just put it on hackage, too) it is as much as a mess as SAML itself. I did once get it to work as a SP, but no longer have access to everything I used to do so, so while I'm happy to help, I might not be as much help as I'd like. I'm sorry I didn't better document it at the time, but was mainly trying to prove haskell was viable for something. If you want to use it for an IdP or anything other than SSO SP, it might be missing some things.

By the end of this I certainly shared some of your opinion of hxt, but it does provide some benefits I couldn't find elsewhere, particularly around namespace management.  The main thing I wanted going into this was not to have to write separate serializer/deserializers for every type or to keep track of namespaces, and despite the syntax being a bit opaque and dependency on obscure libraries, I am quite happy with the simplicity of defining `XmlPickler` classes. I did end up writing some of the [xml-conduit stuff](https://github.com/dylex/invertible/tree/master/conduit) but never switched and I don't remember why.

As for serialization, I think you want to use `SAML2.XML.samlToXML` and `xmlToSAML`. They do some mucking with the namespaces to get it to work.  There's also the slightly higher level `SAML2.Bindings.HTTPPOST.encodeForm` which just does the requisite form/base64 encoding on top (or `HTTPRedirect` depending on your use case). I believe `xmlToSAML` also filters out the xmlpi `<?xml>` header.

**Comment by fisx** [comment]
I'm interested in SSO SP only for now, and yes, I noticed it's not very mature, so no worries.  I'm hoping to use some of this code in our own library.  Also open source.  I'll let you know how it turns out.

I've started off writing xml-conduit parsers with Cursors, now I'm playing with the idea of porting http://hackage.haskell.org/package/JsonGrammar.to xml.  Not sure yet where this is going.

Your hints worked, and I can serialize now.  That doesn't help though if I call `signSAMLProtocol`, since that in turn calls the pickler and I get the same error (even though weirdly after the error the computation continues).

```haskell
test :: IO ()
test = do
  let req = samlauthreq
  req' <- signSAMLProtocol key req
  print $ req'
  req'serialized :: LBS <- pure $ samlToXML req'
  print $ req'serialized
  verif :: AuthnRequest <- verifySAMLProtocol req'serialized
  print verif
```

Also: why does `verifySAMLProtocol` not take any public keys against which to verify?

I'll look into the difference between `Text.XML.HXT.Arrow.Pickle.Xml.Invertible.xpickle` and `SAML2.XML.samlToXML` now.

**Comment by fisx** [comment]
I think this is resolved by #3.

**Comment by dylex** [comment]
Yeah, sorry, not sure I have much to add or time to dig farther in at the moment.  I believe `verifySAMLProtocol` was intended to be able to retrieve the keys itself somehow (or there's some protocol to do so) but I never implemented that. It does seem reasonable at least to take an optional key to validate.

Feel free to do what makes sense here to improve things. I'll at least try to keep up with changes, but happy to add you on hackage as well if that helps.

**Comment by fisx** [comment]
That's fine, your code is valuable to me as it is.  Thanks for inviting me, I might get back to you about co-maintainership in the future.  For now I want to see how far I can get with rendering the problem small and elegant by only supporting a few chosen IdPs and using hsaml2 only as an internal shortcut.
